# Generated by Django 2.2.11 on 2020-03-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='', max_length=255, verbose_name='Heading')),
                ('text_html', models.TextField(default='', verbose_name='Text')),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'About',
                'db_table': 'base_ui_about',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='Title')),
                ('image', models.FileField(blank=True, null=True, upload_to='features_image', verbose_name='Image')),
                ('short_description', models.TextField(default='', verbose_name='Short description')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'base_ui_product',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=255, verbose_name='First name')),
                ('last_name', models.CharField(default='', max_length=255, verbose_name='Last name')),
                ('image', models.FileField(blank=True, null=True, upload_to='features_image', verbose_name='Image')),
                ('priority', models.IntegerField(default=0, verbose_name='Priority')),
                ('roles', models.TextField(default='', verbose_name='Roles')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'db_table': 'base_ui_team',
            },
        ),
    ]
